REM ###################################################################################################################################
REM # Copyright © 2007 Breadboard BI, LLC.  All rights reserved. 									      							  #                                                                                                                                #
REM ###################################################################################################################################

REM This file calls another file that archives the log file.  Update the path for your server.

CD D:\kettle\code\JOBS

CMD.EXE /C ARCHIVE_WEB_LOG_FILES.bat